### ISSUE TITLE
order-info: {"error":24,"result":null}

### ISSUE THREAD

**Issue by lijingpan** [bitkub/bitkub-official-api-docs#1]
/api/market/order-info

Server time: 1569287859
Signing payload: {"id":1734662,"sd":"buy","sym":"THB_USDT","ts":1569287859}
Payload with signature: {"id":1734662,"sd":"buy","sig":"557cf85adc5a1bd54173ebc5c27c56c24b10cf15cc56c018872848510d57073b","sym":"THB_USDT","ts":1569287859}
order-info: {"error":24,"result":null}

Other interfaces are normal

**Comment by wsomrak** [comment]
How?

**Comment by sayobile** [comment]
https://github.com/bitkub/bitkub-official-api-docs/issues/1#issue-497407439

**Comment by bitkub** [comment]
Please re-open the issue if it still persists.
