### ISSUE TITLE
ไม่สามารถใช้ bitkub.tradingview(sym='BTC_THB', int=1, frm='', to='')

### ISSUE THREAD

**Issue by harith11000** [bitkub/bitkub-official-api-docs#117]
เกิด error ขึ้น สามวันที่ผ่านมา ทั้งที่ ก่อนหน้านี้ก็ runได้ตามปรกติ ไม่ทราบว่า ในส่วนของ tradingview ได้มีการเปลี่ยนแปลงอะไรหรือไม่ครับผม 

Exception has occurred: JSONDecodeError
Expecting value: line 1 column 1 (char 0)
StopIteration: 0
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by TakUkaT** [comment]
เป็น เหมือนกันเลยครับผม call API /tradingview/history ได้ response เป็น [502] 
แล้วก็ไป error ที่ response.json() ตามนี้เลยครับ

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by harith11000** [comment]
ครับผม คงต้องรออัพเดท bitkub ผมพึ่งหัดใช้ ขอบคุณครับผม

ในวันที่ จ. 12 มิ.ย. 2023 23:34 TakUkaT ***@***.***> เขียนว่า:

**Comment by rsoutar** [comment]
น่าจะใช้งานได้แล้วมั้ยครับ?

**Comment by harith11000** [comment]
ครับผม ตอนนี้ใช้งานได้ตามปรกติ เป็นที่ server ครับผม

ในวันที่ พ. 14 มิ.ย. 2023 01:38 Richard Soutar ***@***.***>
เขียนว่า:

**Comment by danger2520** [comment]
access_token": "A21AAFnNagckuSeTmuxh76PObGZDBf2Pu3zG9AzZzakdXrIL8KyGmx7eOr_mV0pKpmoiLn8_dxQdaB1miYyrGIxArfofTUxoA",
