### ISSUE TITLE
Request: Public API Exchange Info

### ISSUE THREAD

**Issue by first087** [bitkub/bitkub-official-api-docs#15]
อยากได้ Public API สำหรับข้อมูลของ Exchange เรื่องของเงื่อนไขการวาง Order, เงื่อนไขการถอน เป็นต้น

ตัวอย่างเช่น

1. ข้อมูลการวาง Order
- จำนวนเหรียญขั้นต่ำ เช่น THB 10 บาท, BTC 0.0001 เหรียญ
- จำนวนทศนิยม ต้องไม่เกินกี่หลัก เช่น THB 2 หลัก, BTC 8 หลัก
- สถานะของการวาง Order เช่น เทรดได้, ปิดปรับปรุง

2. ข้อมูลการถอน
- จำนวนเหรียญขั้นต่ำที่ถอนได้ เช่น THB 30 บาท, BTC 0.001 เหรียญ
- ค่าธรรมเนียมในการถอน เช่น THB 20 บาท, BTC 0.0001 เหรียญ
- สถานะการถอน เช่น ถอนได้, ปิดปรับปรุง

ตัวอย่าง Output
```json
{
  "order": {
    "THB": {
      "minPlaceOrder": 10,
      "decimal": 2,
      "enable": true
    },
    "BTC": {
      "minPlaceOrder": 0.0001,
      "decimal": 8,
      "enable": false
    }
  },
  "widthdraw": {
    "THB": {
      "min": 30,
      "fee": 20,
      "enable": true
    },
    "BTC": {
      "min": 0.001,
      "fee": 0.0001,
      "enable": false
    }
  }
}
```

**Comment by bitkub** [comment]
Hi,

Thanks for the suggestion. We will surely implement this.
