### ISSUE TITLE
Can i known transaction date time from /api/market/my-order-history?

### ISSUE THREAD

**Issue by winweb** [bitkub/bitkub-official-api-docs#38]
I tried use ts but it doesn't answer the question.

**Comment by chkob** [comment]
If I'm not mistaken, think that endpoint returns time stamp value in the field 'ts' which is unix time stamp, you may convert them to UTC and add up to your prefer time zone to get local time.

**Comment by winweb** [comment]
@chkob thanks kub.  currently i found solution by ts * 1000 because Bitkub timestamp is in the unit of millisecond while the Javascript timestamp is in the unit of second

EX.

var date = new Date(**ts * 1000**);
console.log("Unix Timestamp:", ts)
console.log("Date Timestamp:", date.getTime())
