### ISSUE TITLE
API /tradingview/history ค่าที่ return กลับมาคือค่าอะไรบ้างครับ

### ISSUE THREAD

**Issue by ohlara** [bitkub/bitkub-official-api-docs#68]
ค่า c, h, l, o, s, t, v ที่ return จาก /tradingview/history คืออะไรบ้างหรอครับ

**Comment by anotheron09** [comment]
c = ราคาปิด (Close Price) 
h = ราคาสูงสุด (High Price)
l = ราคาต่ำสุด (Low Price)
o = ราคาเปิด (Open price)
s = ไม่แน่ใจคิดว่าน่าจะเป็น status 
t = Unix Time Stamp
v = volume
