### ISSUE TITLE
GET /api/market/bids fields are required

### ISSUE THREAD

**Issue by taninaim** [bitkub/bitkub-official-api-docs#8]
Tried running

```python
data = {
    "sym": "THB_DOGE",
    "lmt": 10
}

response = requests.get(
    API_HOST + '/api/market/bids', headers=header, data=json_encode(data))
print('Response: ' + response.text)
```

and the error was 

`Response: {"error":10,"result":{"lmt":["The lmt field is required","The lmt field must be numeric"],"sym":["The sym field is required"]}}`

Is the function not fully implemented?

**Comment by sweet09** [comment]
Ok

**Comment by Marisada** [comment]
`response = requests.get(API_HOST + '/api/market/bids', params=data)`

should be fine.

**Comment by bitkub** [comment]
This should be GET request with url query.
